# Generated by Django 6.0.6 on 2026-06-17 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Краткое био"
                    ),
                ),
                ("portfolio_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="Скрыто до взаимного матча",
                        max_length=100,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("idea", "Есть только идея"),
                            ("prototype", "Прототип / MVP"),
                            ("traction", "Есть пользователи / первые продажи"),
                            ("business", "Работающий бизнес"),
                            ("looking", "Пока просто ищу проект"),
                        ],
                        default="looking",
                        max_length=20,
                    ),
                ),
                (
                    "commitment",
                    models.CharField(
                        choices=[
                            ("hobby", "Хобби (несколько часов в неделю)"),
                            ("part_time", "Part-time (20 часов в неделю)"),
                            ("full_time", "Full-time (40+ часов в неделю)"),
                        ],
                        default="hobby",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(default="Не указан", max_length=100)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="profiles_interested",
                        to="profiles.interestarea",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills_have",
                    models.ManyToManyField(
                        blank=True,
                        related_name="profiles_with_skill",
                        to="profiles.skill",
                    ),
                ),
                (
                    "skills_want",
                    models.ManyToManyField(
                        blank=True,
                        related_name="profiles_seeking_skill",
                        to="profiles.skill",
                    ),
                ),
            ],
        ),
    ]
